my_string=input('Город вашего проживания ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print('Город вашего проживания'.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
